### ISSUE TITLE
dynamic partials cause (lookupProperty(...) || (depth0 && lookupProperty(...)) || alias3).call is not a function

### ISSUE THREAD

**Issue by leonardlin** [express-handlebars/express-handlebars#116]
Used versions:
express-handlebars: 5.1.0
handlesbars: 4.7.6

partials is saved in:
/views/partials/filename.handlesbars
varPartial = 'filename';

main template uses
`{{> (varPartial)}}`

outcome:

TypeError: (lookupProperty(...) || (depth0 && lookupProperty(...)) || alias3).call is not a function
    at Object.eval [as main] (eval at createFunctionContext (/usr/src/app/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:262:23), <anonymous>:11:148)
    at main (/usr/src/app/node_modules/handlebars/dist/cjs/handlebars/runtime.js:208:32)
    at ret (/usr/src/app/node_modules/handlebars/dist/cjs/handlebars/runtime.js:212:12)
    at ret (/usr/src/app/node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:519:21)
    at ExpressHandlebars._renderTemplate (/usr/src/app/node_modules/express-handlebars/lib/express-handlebars.js:253:10)
    at ExpressHandlebars.render (/usr/src/app/node_modules/express-handlebars/lib/express-handlebars.js:166:21)
    at async ExpressHandlebars.renderView (/usr/src/app/node_modules/express-handlebars/lib/express-handlebars.js:224:15)

If I use
`{{> 'filename'}}`

It works

**Comment by UziTech** [comment]
this sounds like an issue for handlebars. express-handlebars doesn't do anything with the handlebars syntax other than pass it to handlebars.

**Comment by joeldenning** [comment]
For anyone else who ran into this, my issue was in providing the dynamic partial name as a string rather than a function that returns a string:

```handlebars
{{>(videoPartial)}}
```

```js
// Works
res.render("view-video", {
  layout: 'app',
  video,
  videoPartial: () => `${purchasedCourse.slug}/${video.slug}`
})

// Doesn't work
res.render("view-video", {
  layout: 'app',
  video,
  videoPartial: `${purchasedCourse.slug}/${video.slug}`
})
```

**Comment by UziTech** [comment]
@knownasilya it would be easier to help if you create a new issue and give more details about the code you are trying.

**Comment by knownasilya** [comment]
I was able to resolve it. I registered a helper that was defined in an ESM but required, so it didn't use `default`.
