### ISSUE TITLE
Running examples/basic ==yields==> Error    Cannot find module '../../'

### ISSUE THREAD

**Issue by JoeCodeswell** [express-handlebars/express-handlebars#196]
Running examples/basic  ==yields==> Error
```powershell
 > node server.js

internal/modules/cjs/loader.js:892
  throw err;
  ^

Error: Cannot find module '../../'
Require stack:
- C:\1d\ExpressWebFrameworkPjs\exphbsbasicapp\server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (C:\1d\ExpressWebFrameworkPjs\exphbsbasicapp\server.js:4:16)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ 'C:\\1d\\ExpressWebFrameworkPjs\\exphbsbasicapp\\server.js' ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! express-handlebars-basic-example@0.0.0 start: `node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the express-handlebars-basic-example@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     
```

Changing examples/basic/server.js   like 
```javascript
//const exphbs = require("../../"); // "express-handlebars"  # WHAT is this?
const exphbs = require("express-handlebars"); //   Joe's guess "express-handlebars"  

```
==yields==>
```powershell
> npm start

> express-handlebars-basic-example@0.0.0 start C:\1d\ExpressWebFrameworkPjs\exphbsbasicapp
> node server.js

express-handlebars example server listening on: 3000
```

**Comment by UziTech** [comment]
If you run the example in this repo `../../` refers to the root of this repo. But you are correct that it should be replaced with `express-handlebars` if you run it in a different folder.
