### ISSUE TITLE
Partial No Longer Resolving once app is deployed to Digital Ocean Cloud.

### ISSUE THREAD

**Issue by CliffordMarley** [express-handlebars/express-handlebars#199]
I have a standard web app with dynamic rendering via express-handlebars. My dev machine is working flawless, but once deployed to the Cloud, my header partial will no longer resolve. Below is the error I am getting:

`[my-app]Error: The partial Header could not be found
[my-app]    at Object.invokePartial (/workspace/node_modules/handlebars/dist/cjs/handlebars/runtime.js:332:11)
[my-app]    at Object.invokePartialWrapper [as invokePartial] (/workspace/node_modules/handlebars/dist/cjs/handlebars/runtime.js:84:39)
[my-app]    at Object.eval [as main] (eval at createFunctionContext (/workspace/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:262:23), <anonymous>:11:28)
[my-app]    at main (/workspace/node_modules/handlebars/dist/cjs/handlebars/runtime.js:208:32)
[my-app]    at ret (/workspace/node_modules/handlebars/dist/cjs/handlebars/runtime.js:212:12)
[my-app]    at ret (/workspace/node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:519:21)
[my-app]    at ExpressHandlebars._renderTemplate (/workspace/node_modules/express-handlebars/lib/express-handlebars.js:261:10)
[my-app]    at ExpressHandlebars.render (/workspace/node_modules/express-handlebars/lib/express-handlebars.js:173:21)
[my-app]    at async ExpressHandlebars.renderView (/workspace/node_modules/express-handlebars/lib/express-handlebars.js:236:12)
`

But this `Header` partial exists and is loaded just fine on my dev machine, but it's no longer working once deployed. What could be the problem and proposed solution?

**Comment by CliffordMarley** [comment]
Well, I fixed it. The problem was not with `express-handlebars`, but rather with GitHub. I am using GitHub CI/CD to auto-deploy changes to my Digital Ocean Droplet, but for some reason, some changes made on my local repo did not get pushed to the remote one, hence deployed inadequate project files. I will do a more in-depth analysis next time before reporting an issue.
