### ISSUE TITLE
Changing the default extension for views does not work (with express 4)

### ISSUE THREAD

**Issue by paul23-git** [express-handlebars/express-handlebars#556]
When using express handlebars with express 4.x in the following manner:

```
    const e = engine({extname: '.hbs'});
    server.engine('handlebars', e);
```

Doesn't update the default extension. If in the views directory a view exist (ie signing.hbs) on the following line an error happens;

```
    return res.render("signin", {client_id: "123", redirect_url: "www.google.com", scope:"read", layout: false});
```

*error*:

```
Error: Failed to lookup view "signin" in views directory "/home/paul/Documents/webasupport/startid/backend/views" at Function.render (/home/paul/Documents/webasupport/startid/backend/node_modules/express/lib/application.js:597:17) at ServerResponse.render (/home/paul/Documents/webasupport/startid/backend/node_modules/express/lib/response.js:1039:7) at doAuthorizationCodeGrant (/home/paul/Documents/webasupport/startid/backend/src/controllers/auth-controller.ts:37:16) at processTicksAndRejections (node:internal/process/task_queues:95:5) at /home/paul/Documents/webasupport/startid/backend/src/controllers/auth-controller.ts:89:20
    view = View {defaultEngine: "handlebars", ext: ".handlebars", name: "signin", root: "/home/paul/Documents/webasupport/startid/backend/views", engine: Function, ...}
```

Even though `signin.hbs` exist. And the details showed that the view still has `ext: ".handlebars"`

Changing the filename to `signin.handlebars` works but isn't really desired.

**Comment by pulli23** [comment]
@UziTech oh, now this confuses me why there is a "extname" option which is indepedent of the one under "server.engine()"

**Comment by UziTech** [comment]
One is for express-handlebars one is for express. Unfortunately I don't think there is a way to get the one from express in express-handlebars.
