### ISSUE TITLE
Partial could not be found 

### ISSUE THREAD

**Issue by namPS** [express-handlebars/express-handlebars#71]
Partial not found error when deployed to Digital Ocean, tried [changing file name](https://github.com/ericf/express-handlebars/issues/174#issuecomment-208381653), adding [hbs.registerPartials](https://stackoverflow.com/questions/49479129/partials-not-found-in-hbs-express-js), but neither works. 

```> open-table-site@1.0.0 assemble /one-table
> node ./bin/tasks/assemble "production"


events.js:160
      throw er; // Unhandled 'error' event
      ^
Error: The partial global/header could not be found
    at Object.invokePartial (/one-table/node_modules/handlebars/dist/cjs/handlebars/runtime.js:332:11)
    at Object.handlebars.VM.invokePartial (/one-table/node_modules/engine-handlebars/index.js:196:26)
    at Object.invokePartialWrapper [as invokePartial] (/one-table/node_modules/handlebars/dist/cjs/handlebars/runtime.js:84:39)
    at Object.eval (eval at createFunctionContext (/one-table/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:262:23), <anonymous>:10:31)
    at main (/one-table/node_modules/handlebars/dist/cjs/handlebars/runtime.js:208:32)
    at ret (/one-table/node_modules/handlebars/dist/cjs/handlebars/runtime.js:212:12)
    at ret (/one-table/node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:519:21)
    at Object.render (/one-table/node_modules/engine-handlebars/index.js:94:14)
    at /one-table/node_modules/engine-cache/index.js:251:14
    at Object.engineRender [as render] (/one-table/node_modules/engine-cache/index.js:287:7)
```
config.js
```
var express = require('express');
var bodyParser = require('body-parser');
const methodOverride = require('method-override');
var errorHandler = require('errorhandler');
var path = require('path');
var exphbs = require('express-handlebars');
const helpers = require( 'handlebars-helpers')();

module.exports = function() {
  var app = express();

  app.engine('.hbs', exphbs({
    extname: '.hbs',
    helpers: require(path.join(__dirname, 'src', 'templates', 'helpers', 'render')),
    layoutsDir: path.join(__dirname, 'src','templates', 'layouts'),
    partialsDir: path.join(__dirname, 'src','templates', 'partials'),
    defaultLayout: 'default'
  }));

  app.set('port', 8080);
  app.set('views', path.join(__dirname, 'src','templates','pages'));
  app.set('view engine', 'hbs');
  app.use(bodyParser.urlencoded({ extended: true }));
  app.use(bodyParser.json());
  app.use(methodOverride());
  app.use(errorHandler());
  app.use(express.static(path.join(__dirname, './build')));

  return app;
}();
```

**Comment by UziTech** [comment]
That stack trace doesn't look like it is using express-handlebars. It looks like this might be an issue for [handlebars](https://github.com/handlebars-lang/handlebars.js) or [engine-handlebars](https://github.com/jonschlinkert/engine-handlebars)

**Comment by namPS** [comment]
It does have express-handlebar, but I'll ask handlebar as well.
FYI Here's dependencies:

``` "dependencies": {
    ...
    "errorhandler": "^1.5.0",
    "express": "^4.16.3",
    "express-handlebars": "^3.0.0",
    "flexboxgrid": "^6.3.1",
    "flexboxgrid-sass": "^8.0.5",
    "fs-extra": "^0.30.0",
    "glob-fs": "^0.1.6",
    "gsap": "^1.19.1",
    "gulp-extname": "^0.2.2",
    "handlebars-helpers": "^0.7.3",
    "imagemin": "^5.3.1",
    ....
  }
```

**Comment by UziTech** [comment]
It does have express-handlebars but that error is not from express-handlebars. Also v3 is very old. You should update to v5 if you can. There have been a few fixes that could fix this error.
