### ISSUE TITLE
bug: partial layout could not be found

### ISSUE THREAD

**Issue by 0xblur** [express-handlebars/express-handlebars#792]
Hi! I'm new to Handlebars. I'm trying to follow the MDN Express Library tutorial using Handlebars and I get this error at render:

```
Error: The partial layout could not be found
    at Object.invokePartial (/home/hadezb/learning/web-development/node/express/locallibrary-tutorial/node_modules/handlebars/dist/cjs/handlebars/runtime.js:332:11)
    at Object.invokePartialWrapper [as invokePartial] (/home/hadezb/learning/web-development/node/express/locallibrary-tutorial/node_modules/handlebars/dist/cjs/handlebars/runtime.js:84:39)
    at Object.eval [as main] (eval at createFunctionContext (/home/hadezb/learning/web-development/node/express/locallibrary-tutorial/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:262:23), <anonymous>:10:31)
    at main (/home/hadezb/learning/web-development/node/express/locallibrary-tutorial/node_modules/handlebars/dist/cjs/handlebars/runtime.js:208:32)
    at ret (/home/hadezb/learning/web-development/node/express/locallibrary-tutorial/node_modules/handlebars/dist/cjs/handlebars/runtime.js:212:12)
    at ret (/home/hadezb/learning/web-development/node/express/locallibrary-tutorial/node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:519:21)
    at ExpressHandlebars._renderTemplate (/home/hadezb/learning/web-development/node/express/locallibrary-tutorial/node_modules/express-handlebars/dist/express-handlebars.js:244:16)
    at ExpressHandlebars.<anonymous> (/home/hadezb/learning/web-development/node/express/locallibrary-tutorial/node_modules/express-handlebars/dist/express-handlebars.js:156:31)
    at Generator.next (<anonymous>)
    at fulfilled (/home/hadezb/learning/web-development/node/express/locallibrary-tutorial/node_modules/express-handlebars/dist/express-handlebars.js:10:58)
```
You can check the complete project code [HERE](https://github.com/0xblur/mdn-express-library), but I'll also post relevant excerpts for you to debug below:
```js
//routes/index.js
import express from "express";
const router = express.Router();

/* GET home page. */
router.get("/", (req, res, next) => {
	res.redirect("/catalog");
});

export default router;
```

```js
//routes/catalog.js
router.get("/", BookController.index);
```

```js
//controllers/BookController.js
res.render("index", {
			title: "Local Library Home",
			book_count: numBooks,
			book_instance_count: numBookInstances,
			book_instance_available_count: numAvailableBookInstances,
			author_count: numAuthors,
			genre_count: numGenres,
		});
```

```js
//views/index.hbs
<h1>{{ title }}</h1>
<p>
    Welcome to <em>LocalLibrary</em>, a very basic Express website developed as a tutorial example on the Mozilla Developer Network.
</p>
<p>The library has the following record counts:</p>
<ul>
    <li>
        <strong>Books:</strong>{{ book_count }}
    </li>
    <li>
        <strong>Copies:</strong>{{ book_instance_count }}
    </li>
    <li>
        <strong>Copies available:</strong>{{ book_instance_available_count }}
    </li>
    <li>
        <strong>Authors:</strong>{{ author_count }}
    </li>
    <li>
        <strong>Genres:</strong>{{ genre_count }}
    </li>
</ul>
```
```hbs
//views/layouts/main.hbs
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title></title>
        <link rel="stylesheet"
              href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css"
              integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N"
              crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
                integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
                crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js"
                integrity="sha384-+sLIOodYLS7CIrQpBjl+C7nPvqq+FbNUBDunl/OZv93DB7Ln/533i8e/mZXLi/P+"
                crossorigin="anonymous"></script>
        <link rel="stylesheet" href="/stylesheets/style.css">
    </head>
    <body>
        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-2">
                    {{>sidebar}}
                    <div class="col-sm-10">{{ body }}</div>
                </div>
            </div>
        </div>
    </body>
    <footer>
        {{> footer}}
    </footer>
</html>
```

**Comment by 0xblur** [comment]
The issue was with the `render("error")` template that had an erroneous layout being imported.
